name: 'workflow trigger'
description: 'Trigger another workflow in the same repo using workflow dispatch'
inputs:
  workflow:  # workflow id or name
    description: 'id or name of the workflow to be triggered'
    required: true
  token:  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
    description: 'Github PAT'
    required: true
  ref:
    description: 'ref'
    required: true
  inputs:
    description: 'Inputs to be sent'
    required: true
    default: '{}'
outputs:
  response: # response of invoking the dispatch event
    description: 'response for invoking'
runs:
  using: 'node12'
  main: 'dist/index.js'
