name: "dispatch-test"
on: 
  workflow_dispatch:
    inputs:
      status:
        description: 'Status of the previous workflow'     
        required: true
        default: 'passed'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level:: ${{ github.event.inputs.inputs }}"
